# Generated by Django 5.2.6 on 2026-08-07 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('trigger_reason', models.CharField(choices=[('onboarding', 'Onboarding'), ('manual_retake', 'Manual Retake'), ('diary_flagged', 'Diary Flagged')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('state', models.CharField(max_length=40)),
                ('smoking_status', models.CharField(choices=[('never', 'Never smoked'), ('former_5plus_years', 'Former smoker, quit 5+ years ago'), ('former_under_5_years', 'Former smoker, quit under 5 years ago'), ('current', 'Current smoker')], max_length=25)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('bmi_category', models.CharField(max_length=20)),
                ('activity_level', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], max_length=10)),
                ('high_sodium', models.BooleanField(default=False)),
                ('low_fruit_veg', models.BooleanField(default=False)),
                ('screened_past_2yrs', models.BooleanField(default=True)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_hypertension', models.BooleanField(default=False)),
                ('has_high_cholesterol', models.BooleanField(default=False)),
                ('modifiable_lifestyle_score', models.PositiveSmallIntegerField()),
                ('risk_band', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], max_length=10)),
                ('score_factors', models.JSONField()),
                ('calculation_trace', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=40)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ms', models.CharField(max_length=200)),
                ('detail_en', models.TextField()),
                ('detail_ms', models.TextField()),
                ('requires_clinic_visit', models.BooleanField(default=False)),
                ('target_facility_type', models.CharField(blank=True, max_length=50)),
                ('is_priority_ranked', models.BooleanField(default=False)),
                ('priority_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='assessments.riskassessment')),
            ],
            options={
                'ordering': ['priority_rank', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='one_current_assessment_per_user'),
        ),
    ]
