# Generated by Django 5.2.6 on 2026-08-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('facility_subtype', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=40)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField()),
                ('postcode', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='clinics_cli_state_a519f0_idx')],
            },
        ),
    ]
