# Generated by Django 5.2.6 on 2026-08-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('facility_subtype', models.CharField(blank=True, max_length=150)),
                ('sector', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(max_length=40)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField()),
                ('town', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='clinics_cli_state_a519f0_idx'), models.Index(fields=['category'], name='clinics_cli_categor_434f30_idx')],
            },
        ),
    ]
