ACTION_RULES = {
    "SMOKING_CURRENT_MQUIT": {
        "title_en": "Quit Smoking Support",
        "title_ms": "Sokongan Berhenti Merokok",
        "detail_en": "Schedule a consult at an MOH mQuit Clinic for behavioural counselling and nicotine replacement therapy.",
        "detail_ms": "Tempah temu janji di Klinik mQuit KKM untuk kaunseling tingkah laku dan terapi gantian nikotin.",
        "requires_clinic_visit": True, "target_facility_type": "mquit_clinic",
        "rank_group": "smoking",
    },
    "BMI_OBESE_DIETITIAN": {
        "title_en": "Dietitian Consultation",
        "title_ms": "Rundingan Pakar Pemakanan",
        "detail_en": "Consult a dietitian at your nearest Klinik Kesihatan for a structured caloric deficit plan.",
        "detail_ms": "Berjumpa pakar pemakanan di Klinik Kesihatan berdekatan untuk pelan defisit kalori berstruktur.",
        "requires_clinic_visit": True, "target_facility_type": "klinik_kesihatan",
        "rank_group": "activity_bmi",
    },
    "ACTIVITY_INACTIVE_TARGET": {
        "title_en": "Get Moving",
        "title_ms": "Mulakan Aktiviti Fizikal",
        "detail_en": "Target 150 minutes/week of moderate aerobic activity — e.g. a 30-minute brisk walk, 5 days a week.",
        "detail_ms": "Sasarkan 150 minit/minggu aktiviti aerobik sederhana — contohnya jalan pantas 30 minit, 5 hari seminggu.",
        "requires_clinic_visit": False, "target_facility_type": "",
        "rank_group": "activity_bmi",
    },
    "HIGH_SODIUM_DASH": {
        "title_en": "Reduce Sodium Intake",
        "title_ms": "Kurangkan Pengambilan Natrium",
        "detail_en": "Adopt DASH diet principles; limit salt to under 1 tsp (5g sodium) per day.",
        "detail_ms": "Amalkan prinsip diet DASH; hadkan garam kepada kurang 1 sudu teh (5g natrium) sehari.",
        "requires_clinic_visit": False, "target_facility_type": "",
        "rank_group": None,
    },
    "LOW_FRUIT_VEG_INCREASE": {
        "title_en": "Increase Fruit & Vegetable Intake",
        "title_ms": "Tingkatkan Pengambilan Buah & Sayur",
        "detail_en": "Increase to at least 2 servings of fruit and 3 servings of vegetables a day (Suku Suku Separuh).",
        "detail_ms": "Tingkatkan kepada sekurang-kurangnya 2 hidangan buah dan 3 hidangan sayur sehari (Suku Suku Separuh).",
        "requires_clinic_visit": False, "target_facility_type": "",
        "rank_group": None,
    },
    "SCREENING_BASELINE": {
        "title_en": "Book a Health Screening",
        "title_ms": "Tempah Saringan Kesihatan",
        "detail_en": "Book a baseline screening (fasting blood glucose, lipid profile, blood pressure) at a nearby public clinic.",
        "detail_ms": "Tempah saringan asas (glukosa darah puasa, profil lipid, tekanan darah) di klinik awam berdekatan.",
        "requires_clinic_visit": True, "target_facility_type": "klinik_kesihatan",
        "rank_group": None,
    },
    "DIABETES_ANNUAL_SCREENING": {
        "title_en": "Diabetic Screening",
        "title_ms": "Saringan Diabetes",
        "detail_en": "Schedule annual diabetic foot and retinopathy screening; monitor home glucose regularly.",
        "detail_ms": "Jadualkan saringan kaki diabetik dan retinopati setiap tahun; pantau glukosa di rumah secara berkala.",
        "requires_clinic_visit": True, "target_facility_type": "klinik_kesihatan",
        "rank_group": None,
    },
    "HYPERTENSION_BP_LOG": {
        "title_en": "Manage Blood Pressure",
        "title_ms": "Urus Tekanan Darah",
        "detail_en": "Maintain a daily home blood pressure log (target under 130/80 mmHg); review medication adherence.",
        "detail_ms": "Simpan log tekanan darah harian di rumah (sasaran bawah 130/80 mmHg); semak kepatuhan ubat.",
        "requires_clinic_visit": False, "target_facility_type": "",
        "rank_group": None,
    },
    "CHOLESTEROL_LIPID_PANEL": {
        "title_en": "Manage Cholesterol",
        "title_ms": "Urus Kolesterol",
        "detail_en": "Schedule a fasting lipid panel every 6–12 months; reduce saturated fat intake.",
        "detail_ms": "Jadualkan ujian lipid puasa setiap 6-12 bulan; kurangkan pengambilan lemak tepu.",
        "requires_clinic_visit": True, "target_facility_type": "klinik_kesihatan",
        "rank_group": None,
    },
}