# Generated by Django 5.2.6 on 2026-08-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DosmLifeExpectancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_band', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('state', models.CharField(max_length=40)),
                ('e_x', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('age_band', 'sex', 'state'), name='unique_dosm_row')],
            },
        ),
    ]
